<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>wio</string>
	</array>
	<key>name</key>
	<string>Informix Wio</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#sql-variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sql-string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#wio-variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#wio-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#wio-keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#mivar-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string-double</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string-single</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#html-tag</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>html-tag</key>
		<dict>
			<key>begin</key>
			<string>\&lt;(?!\?)(?i)</string>
			<key>comment</key>
			<string>html like tag</string>
			<key>end</key>
			<string>(?&lt;!mivar)\&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#mivar-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wio-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wio-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single</string>
				</dict>
			</array>
		</dict>
		<key>mivar-block</key>
		<dict>
			<key>begin</key>
			<string>(?i)(&lt;\?MIVAR[ ]?)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.wio</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.wio</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>wio mivar block &lt;?MIVAR .......&gt; &lt;?/MIVAR&gt; OR &lt;?MIVAR&gt; multiline &lt;?/MIVAR&gt;</string>
			<key>end</key>
			<string>(?i)(&lt;\?/MIVAR&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#wio-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wio-variable-name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wio-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-table</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-column</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-tag</string>
				</dict>
			</array>
		</dict>
		<key>sql-column</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.wio</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.wio</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.wio</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.wio</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>sql column name</string>
			<key>match</key>
			<string>(([a-z]{0,4}[0-9]{0,3})\.([a-z]{1}[a-z0-9_]{2,15}|\*)|([a-z]{1}[a-z_0-9]{2,20}|[a-z]{1}[0-9]{3}))(?=[ ),+\-*/=;\n\[\|"])</string>
		</dict>
		<key>sql-keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.wio</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>sql keyword</string>
			<key>match</key>
			<string>\b(?i)(SELECT|OR|WHERE|FROM|IS|AND|ORDER BY|CASE|WHEN|DISTINCT|UNION|ELSE|END|THEN|OUTER|GROUP BY|IN|TRIM|REPLACE|NULL|BETWEEN|TODAY|MIN|MAX|SUBSTR|FIRST [0-9]{1,5}|DATE|DESC|NOT|SUM|ROUND|count|EXECUTE|PROCEDURE|MOD|MDY|INSERT INTO|NVL|UPDATE|SET|LIKE|CURRENT|YEAR|MONTH|DAY)\b</string>
		</dict>
		<key>sql-string</key>
		<dict>
			<key>begin</key>
			<string>(?i)(RESULTS=([a-z]{1}[\w_\d]*) )?SQL=(\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.wio</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.wio</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>sql string block SQL=""</string>
			<key>end</key>
			<string>(\")(?i)( RESULTS=([a-z]{1}[\w_\d]*))?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.wio</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.wio</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sql-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-table</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-column</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wio-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wio-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double</string>
				</dict>
			</array>
		</dict>
		<key>sql-table</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.wio</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>sql table name</string>
			<key>match</key>
			<string>([a-z]{4}[0-9]{3}[wt]{0,1}(?:[, ][a-z])?\b)</string>
		</dict>
		<key>sql-variable</key>
		<dict>
			<key>comment</key>
			<string>wio misql variable $1, $2....</string>
			<key>match</key>
			<string>\$\d+</string>
			<key>name</key>
			<string>entity.name.function.wio</string>
		</dict>
		<key>string-double</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\|\))\"</string>
			<key>comment</key>
			<string>double quoted string</string>
			<key>end</key>
			<string>(?&lt;!\\)\"</string>
			<key>name</key>
			<string>string.quoted.double.wio</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#wio-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mivar-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wio-keyword</string>
				</dict>
			</array>
		</dict>
		<key>string-single</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)\'</string>
			<key>comment</key>
			<string>single quoted string</string>
			<key>end</key>
			<string>(?&lt;!\\)\'</string>
			<key>name</key>
			<string>string.quoted.single.wio</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#wio-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wio-keyword</string>
				</dict>
			</array>
		</dict>
		<key>wio-block</key>
		<dict>
			<key>comment</key>
			<string>wio block tag</string>
			<key>match</key>
			<string>\&lt;\?[/]?(MIBLOCK|MISQL|MIELSE|(?!mivar|MIVAR))(?:[^ &gt;]+)?[&gt;]?</string>
			<key>name</key>
			<string>keyword.control.wio</string>
		</dict>
		<key>wio-keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.wio</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.wio</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>wio function keyword</string>
			<key>match</key>
			<string>(\$)\(([=&gt;&lt;\+-\/\*]=?|URLENCODE|VECSIZE|VECAPPEND|WEBUNHTML|XOR|XST|SEPARATE|SETVAR|STRFILL|STRLEN|SUBSTR|TRACEMSG|TRIM|TRUNC|UNSETVAR|UPPER|URLDECODE|NXST|OR|PARSE|POSITION|REPLACE|ROUND|NTH|INDEX|ISNOVALUE|ISNULL|ISINT|ISNUM|LOWER|MOD|NC|NE|NOT|IF|EC|EQ|EVAL|EXIT|FIX|HTTPHEADER|IF|DEFER|AND|CONCAT)</string>
		</dict>
		<key>wio-variable</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.wio</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.wio</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>wio variable $var, $str...</string>
			<key>match</key>
			<string>\$[a-zA-Z]{1}[a-zA-Z_0-9]*(\.[0-9]{1,2})?(\.[\w_]+)?</string>
			<key>name</key>
			<string>constant.language.wio</string>
		</dict>
		<key>wio-variable-name</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.wio</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.wio</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>wio varialbe NAME=var</string>
			<key>match</key>
			<string>(?i)NAME=([a-zA-Z0-9_]+).*?(&gt;)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.wio</string>
	<key>uuid</key>
	<string>88f280c3-991d-4136-b948-5290c35a8daf</string>
</dict>
</plist>
